#!/bin/sh /etc/rc.common
 
START=10
STOP=15


start() {  
    # INTERFACE - name of interface who get mac address
    export INTERFACE="wlan0"
    # url for send request
    export URL="http://89.110.99.210"
    export PORT="3000"
    
    # timeout between requests
    export TIMEOUT="5"

    # if necessary set headers to request
    export CustomHeader="Content-Type: application/json"

    # if neccesary add path for request 
    # for example if CustomPath is '/my/custom/path' then request get to url:port/my/custom/path?mac-addr=...
    export CustomPath="status"
    /bin/send_router_stat.sh &
}                 
 
stop() {
    kill $(ps | grep "send_router_stat" | grep -v grep | awk '{print $1}')
    unset NTERFACE
    unset PORT
    unset CustomHeader
    unset CustomPath
}

restart() {
    stop;
    start;
}